# Generated by Django 5.0.1 on 2024-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corse_title', models.CharField(max_length=255)),
                ('course_desc', models.TextField()),
                ('course_img', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=30)),
            ],
        ),
    ]
