# Generated by Django 5.0.1 on 2024-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='corse_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
