# Generated by Django 5.0.1 on 2024-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_corse_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="corse_title",
            new_name="course_title",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_img",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
