# Generated by Django 5.0.1 on 2024-02-02 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Jobseeker'), ('student', 'Student')], default='employer', max_length=10),
        ),
    ]
