# Generated by Django 5.0.1 on 2024-02-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_bio_user_createdat_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
