# Generated by Django 4.2.7 on 2024-01-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_skill_experience_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_name',
        ),
    ]
