# Generated by Django 5.0.1 on 2024-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usertype",
            field=models.CharField(max_length=10),
        ),
    ]
