# Generated by Django 4.2.7 on 2024-01-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_email_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
