# Generated by Django 5.0.1 on 2024-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.CharField(default="NO", max_length=5),
        ),
    ]
