# Generated by Django 4.0.6 on 2024-01-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_education_degree_alter_skill_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
    ]
