# Generated by Django 4.0.6 on 2024-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_rename_email_employer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
