# Generated by Django 4.0.6 on 2024-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_name',
            field=models.CharField(default='Not Mention', max_length=100),
            preserve_default=False,
        ),
    ]
